### ISSUE TITLE
W kodach qr z biletów zawarte jest mniej bajtów niż program wymaga

### ISSUE THREAD

**Issue by whatkindofmilkuare** [sp5wwp/KM_reader#1]
Zazwyczaj kody qr zawierają ciągi znaków zakodowane w base64 które po dekodowaniu dają mniej danych niż 94 bajty

**Comment by sp5wwp** [comment]
Dobrze by było wstawić tu przykład takiego biletu.

**Comment by whatkindofmilkuare** [comment]
Przykładowy ciąg base64:

AwIgS0NCtoYMAkAAHwBMABZvlxsAxZcb/1G/G+MIqQAwMDAwMDAwMDAwMC4CFQDNMsZglOkHejIUGWVZekHqkl9xswIVAJhDtEW94KCZ4y33Ybjwx32AE0mY

**Comment by sp5wwp** [comment]
Bez danych z biletu na wiele się to nie przyda.

**Comment by whatkindofmilkuare** [comment]
OFERTA: BILET ODCINKOWY
MIESIECZNY IMIENNY TAM/
POWRÓT (31)
Numer biletu: CK 210155074
Ulga: Dziecko/Uczen (bilet odcinkowy
miesieczny imienny), 49%, 76, D/U-M
Liczba pasazerów: 1
Wazny od: 02.09.2024 00:00
Wazny do: 01.10.2024 23:59
Data zakupu: 01.09.2024 17:53
Cena: 163,86 zł

**Comment by sp5wwp** [comment]
Wrzuciłem do repo plik .odf z moją analizą danych z 2018r. Na pewno są jakieś zmiany :)

**Comment by whatkindofmilkuare** [comment]
Bardzo dziękuję bo po zobaczeniu że to repozytorium jest już nieaktualne nabrałem chęci aby napisać aktualny dekoder kodów qr

**Comment by sp5wwp** [comment]
> Przykładowy ciąg base64:
> 
> AwIgS0NCtoYMAkAAHwBMABZvlxsAxZcb/1G/G+MIqQAwMDAwMDAwMDAwMC4CFQDNMsZglOkHejIUGWVZekHqkl9xswIVAJhDtEW94KCZ4y33Ybjwx32AE0mY

Możesz tu wrzucić w komentarzu zdekodowane w postaci hex.

**Comment by sp5wwp** [comment]
```
03 02 20 4B 43 42 B6 86
0C 02 40 00 1F 00 4C 00
16 6F 97 1B 00 C5 97 1B
FF 51 BF 1B E3 08 A9 00
30 30 30 30 30 30 30 30
30 30 30 2E 02 15 00 CD
32 C6 60 94 E9 07 7A 32
14 19 65 59 7A 41 EA 92
5F 71 B3 02 15 00 98 43
B4 45 BD E0 A0 99 E3 2D
F7 61 B8 F0 C7 7D 80 13
49 98
```

`4B 43 42 B6 86 0C` to numer serii w formacie little-endian. `CK` jako `KC` a potem `42 B6 86 0C` (=210155074).
`02 40` to cena biletu w groszach (16386). Znowu little-endian.
etc.

**Comment by sp5wwp** [comment]
`4B 43 42 B6 86 0C` to numer serii w formacie little-endian. `CK` jako `KC` a potem `42 B6 86 0C` (=210155074).
`02 40` to cena biletu w groszach (16386). Znowu little-endian.
etc.

**Comment by whatkindofmilkuare** [comment]
Jedynie co pozostaje błędnie wyświetlone to daty. Wartości OF i ulgi wyświetlały się prawidłowo używając repo z 2018 więc nie ma tutaj chyba nic do aktualizacji.

**Comment by whatkindofmilkuare** [comment]
Daty zapisane są w 4 bajtach w formie liczby sekund która upłyneła od 1 stycznia 2010 roku ale należy przesunąć bajty o jeden w stecz względem tego jak było to w repo z 2018

**Comment by whatkindofmilkuare** [comment]
Bajty w których znajdują się numery ibnr stacji również należy przesunąć o jeden bajt wstecz względem repo z 2018

**Comment by sp5wwp** [comment]
Otworzyłem osobny issue (#2), bo problem nie został rozwiązany.
